### ISSUE TITLE
the new sprites don't look that good

### ISSUE THREAD

**Issue by FNFfan1** [cuckydev/PSXFunkin#1]
in my opinion the previous sprites looked a lot better than the new ones in 0.4

**Comment by cuckydev** [comment]
This is because the art has been converted from 8bpp to 4bpp to save RAM. I imagine that with enough manual tweaking it can look just fine, though. With this not being an 'actual issue' I'll just close this.

**Comment by FNFfan1** [comment]
Okay thank you

**Comment by CyndaquilDAC** [comment]
> This is because the art has been converted from 8bpp to 4bpp to save RAM. I imagine that with enough manual tweaking it can look just fine, though. With this not being an 'actual issue' I'll just close this.

ill see if i can do general art cleanup so it doesn't look as obviously lowered in quality
