### ISSUE TITLE
Nitpick/Bugfix? Kapi Not In Freeplay

### ISSUE THREAD

**Issue by otherlego** [cuckydev/PSXFunkin#10]
I like the new addition of the Kapi Mod, but It'd be nice to have it on the freeplay menu.

**Comment by otherlego** [comment]
I also wanna say that what youve been doing is great so far, keep up the work man!

**Comment by cuckydev** [comment]
The plan is for the mod section to have its own stage select, however I hadn't finished the mod screen or kapi itself so it hasn't been made yet.
