### ISSUE TITLE
Tutorial have Dad on GF

### ISSUE THREAD

**Issue by BurAndBY** [cuckydev/PSXFunkin#12]

**Comment by FNFfan1** [comment]
This is because they haven't implemented the graphics for any weeks except week 4 and 7 yet

**Comment by BurAndBY** [comment]
> This is because they haven't implemented the graphics for any weeks except week 4 and 7 yet

He could just remove dad from GF. No need in animations.

**Comment by cuckydev** [comment]
FNFfan1 is correct

**Comment by BurAndBY** [comment]
I think you did not understand my issue, we have this - 
![image](https://user-images.githubusercontent.com/48630651/124432601-785c5e00-dd7a-11eb-82cd-cc0a61eb65f4.png)

**Comment by FNFfan1** [comment]
Yeah, the reason for this is the girlfriend back there is just the girlfriend radio that appears in every stage, and daddy dearest is in the position of where girlfriend would be, I don't know why you'd have to ask CuckyDev that.

**Comment by BurAndBY** [comment]
> Yeah, the reason for this is the girlfriend back there is just the girlfriend radio that appears in every stage, and daddy dearest is in the position of where girlfriend would be, I don't know why you'd have to ask CuckyDev that.

Well, I guess I need to open another issue
