### ISSUE TITLE
[BUG] Daddy Dearest over GF in tutorial level

### ISSUE THREAD

**Issue by BurAndBY** [cuckydev/PSXFunkin#13]
![image](https://user-images.githubusercontent.com/48630651/124444831-aac08800-dd87-11eb-8c53-d02b9761e956.png)
>FNFfan1: Yeah, the reason for this is the girlfriend back there is just the girlfriend radio that appears in every stage, and daddy dearest is in the position of where girlfriend would be, I don't know why you'd have to ask CuckyDev that.

**Comment by FNFfan1** [comment]
GF is not actually a character, its the GF that is in every stage. if you removed daddy dearest it wouldnt matter because gf doesnt have a left, right, up, and down animation.

**Comment by BurAndBY** [comment]
> GF is not actually a character, its the GF that is in every stage. if you removed daddy dearest it wouldnt matter because gf doesnt have a left, right, up, and down animation.

It would be ok if she won't have animation. As fix you can put another GF with animations.

**Comment by BurAndBY** [comment]
>(S)He could just remove dad from GF. No need in animations.

**Comment by cuckydev** [comment]
you already made this issue, I said it's not an issue or a bug and closed it.
