### ISSUE TITLE
South's Vocal Offbeat

### ISSUE THREAD

**Issue by PootisDaMan** [cuckydev/PSXFunkin#14]
South's vocals are are offbeat from the instrumentals. Unsure if that was intentional or an oversight. This song seems to be the only one that has problems.

**Comment by cuckydev** [comment]
I'm not sure why this is, the vocals should be ripped straight from Newgrounds' servers. I tried reimporting them a while ago to fix it but it seems to have not worked.

**Comment by PootisDaMan** [comment]
I can see what I can do.. The vocals and instrumentals are XA right?

**Comment by cuckydev** [comment]
they're 1x drive speed interleaved and only store the XA data (2336 bytes, instead of the full sector 2352). I can imagine some super shit tools would have an indescribable amount of trouble here

**Comment by PootisDaMan** [comment]
Okay, so jPSXdec managed to let me view the audio files. By chance, what program did you use to import the songs?

**Comment by cuckydev** [comment]
I used the tools you can find at https://github.com/ChenThread/candyk-psx

**Comment by PootisDaMan** [comment]
Sadly, I could figure out how to use these tools so I just will send a copy of the song with the fixed vocals. I just used the itch.io version's vocals and instrumentals and combined them.
[South_Inst.zip](https://github.com/cuckydev/PSXFunkin/files/6788765/South_Inst.zip)

**Comment by cuckydev** [comment]
Finally fixed in https://github.com/cuckydev/PSXFunkin/commit/e34881311395df4e8d2af7bd8de0f5012333f114
