### ISSUE TITLE
For CuckyDev

### ISSUE THREAD

**Issue by AlexXDAlX** [cuckydev/PSXFunkin#17]
Hello, I'm sorry for asking you this over and over again but what I want to ask is if you have planned to cancel Friday Night Funkin PS1 Port because you have not uploaded any test but he told me for sure the project is progressing much more trying to complete it quickly but Sorry if I'm so annoying and you're also going to make a minecraft for ps1 or I don't know if I'm wrong but if you're taking a break, it's fine, you need it because you're very good at doing all that in just 1 2 or 3 months, but you are doing this very good, Ok ehh, good bye, take care 

PD: And sorry for the bad english i translated from google

**Comment by Sinfulgamer43** [comment]
translate*

**Comment by AlexXDAlX** [comment]
Oh sorry

**Comment by otherlego** [comment]
15 days isnt too long. I doubt he has plans to work on any other projects currently, and since he isnt getting paid for this he can work however long he needs. It sure its working on fine.

**Comment by AlexXDAlX** [comment]
you are right 15 days are not long
