### ISSUE TITLE
Strange hold notes at the start of Monster

### ISSUE THREAD

**Issue by milkyjd** [cuckydev/PSXFunkin#18]
Before BF starts singing, Dad has some holding notes, and he also starts to repeat after BF. After that the songs goes as it supposed to be. (Normal difficulty, emulated on PSP).
![20210716214845](https://user-images.githubusercontent.com/76964925/125995126-8a5cbbbf-09c9-4fe1-b5c4-d0b38748724c.png)
![20210716214851](https://user-images.githubusercontent.com/76964925/125995133-f6973969-5af4-4cec-ab6d-fa71ca87083c.png)

**Comment by cuckydev** [comment]
could you go into more detail? the charts should be ported correctly. I'll check myself real quick

**Comment by cuckydev** [comment]
the charts are identical between the port and the version on newgrounds. not sure what version of the chart you were expecting, likely a fan version? https://youtu.be/i4pbxHXS8ck

**Comment by milkyjd** [comment]
oh, got it
thanks for answering
