### ISSUE TITLE
Enhancement: Make Week 7 Watchtower bop like the official version

### ISSUE THREAD

**Issue by CyndaquilDAC** [cuckydev/PSXFunkin#2]
I don't really know how PS1 development works, so I can't really tell if this is plausible or even possible, but I'm just throwing it out there.

**Comment by cuckydev** [comment]
I think the main issue is that the bopping is a little too strong? If I'm remembering correctly the bopping in the original is literally just squashing the entire tower, which is why I did it in-code here. Perhaps I should try to turn it down a bit.

**Comment by CyndaquilDAC** [comment]
> I think the main issue is that the bopping is a little too strong? If I'm remembering correctly the bopping in the original is literally just squashing the entire tower, which is why I did it in-code here. Perhaps I should try to turn it down a bit.

It does squash the tower but it also bops his head so it looks a little off
