### ISSUE TITLE
You help me?  please read me

### ISSUE THREAD

**Issue by RokendemonGameplays** [cuckydev/PSXFunkin#22]
A long time ago I always wanted to do game ports (like Minecraft among others) and I don't know how to do it, and since you have made a Port (the one from fnf) can you explain to me how to make one?  Thanks a lot

**Comment by cuckydev** [comment]
that's something I couldn't possibly just explain/teach someone

**Comment by RokendemonGameplays** [comment]
Oh, ok Thanks anyway, I'll continue with the doubt jaja

**Comment by RokendemonGameplays** [comment]
a and bro, your work is very good, you recreated it very well, and when
will you put the tricky mod that you put in the description? but you don't
have to do it, I just ask
