### ISSUE TITLE
[ANOTHER FUN FACT] (sorry)

### ISSUE THREAD

**Issue by Makoto40renta** [cuckydev/PSXFunkin#27]
you can play this on a ps2 too using its retrocompatibility.
i did that using popstarter and open ps2 loader.
it works fine, but when you miss a lot in a song, the vocal starts to desync, but besides that it works good.

(btw, i dont know if that's intentional, but in the "mods" menu, the cross button doesn't select, but TRIANGLE button does)
(its just in that menu)

**Comment by cuckydev** [comment]
stop posting fun facts here

**Comment by BurAndBY** [comment]
> stop posting fun facts here

haha fun facts go brrrrrrrrrrrrrrrrrrr
