### ISSUE TITLE
Mods

### ISSUE THREAD

**Issue by MooseGiraffeYT** [cuckydev/PSXFunkin#32]
Will VS Shaggy or VS Bob get added and When will kapi have sprites?

**Comment by 128x16** [comment]
>VS Shaggy

yes but only if cucky adds support for this controller:
![swag](https://user-images.githubusercontent.com/51507746/128720893-a991cd54-a1dc-4764-a90e-017a109713ea.png)

**Comment by MooseGiraffeYT** [comment]
he doesn't need to x and triangle can be part of 6 note

**Comment by UNSTOP4BLE** [comment]
他們的's controller be like:
