### ISSUE TITLE
[Suggestion] Adding a 16:9 option

### ISSUE THREAD

**Issue by Girotin** [cuckydev/PSXFunkin#35]
I know, I know that this is a simple homebrew PS1 port, and that the console lived in a time where 16:9 screens were still far from existing, buuuut some few games managed to have an Widescreen option at the time with anamorphic image scaling;

This is just a suggestion ok? Don't get the idea that I'm saying "THIS PORT NEED 16:9 WTF??????" cuz that isn't the intention, it's perfectly enjoyable at 4:3 ~ I'm just suggesting this cuz I've seen a good amount of people playing it on PSPs and Vitas, and the black bars look kinda weird to such a recent game on "newer" devices.

It isn't possible to add an regular Widescreen option obviously due to hardware limitations, but some devs at the time managed to make 16:9 on the PS1 possible with a technique called for some people as "Anamorphic Scaling", and in easier words for this specific topic ~ Squeezing an image to re-stretch it on the right way.

![EX1](https://user-images.githubusercontent.com/45373992/129125012-9a47e1c5-0256-49eb-8a21-cc7273ea92fb.png)

Here we have an 16:9 image, squeezed out on a 4:3 aspect ratio

![EX2](https://user-images.githubusercontent.com/45373992/129125055-acfae29b-6d2d-4cf4-b12c-6a39cc89577f.png)

And here's the same image re-stretched back to 16:9 

That's basically the method that games like Bloody Roar 2 and V-Rally 2 utilize to give us an 16:9 image without changing the game's resolution.

I don't know how complicated it should be to program something like this, or if this project would have interest in making such a thing, but here's the idea.

Grab it if you like it and wanna do it, or simply ignore if u don't think it's necessary/ it's going to need to much work to be worth doing.

**Comment by UNSTOP4BLE** [comment]
im on a psp lol
