### ISSUE TITLE
Picture freeze

### ISSUE THREAD

**Issue by Spongbobby** [cuckydev/PSXFunkin#4]
When I boot up the game on my Wii (wiisxrx is the emulator). the picture freezes in just under a second (except for backgrounds, health bar and score) and every note registers as a miss even if I hit them at the correct time, And hit them correctly. I’m only using the funkin.iso file so if there’s any files I need to add or any ways to troubleshoot past this I would love to know.

**Comment by cuckydev** [comment]
This sounds like an issue with the emulator you're using. As long as the game works on original PlayStation hardware, which it does to my knowledge, this isn't something I'll be looking into.
