### ISSUE TITLE
Im mods i have a problem

### ISSUE THREAD

**Issue by RokendemonGameplays** [cuckydev/PSXFunkin#58]
hello I have a problem with a mod, the tricky mod and expurgation, when there is a long arrow the tank man stays still and does not move, but in the normal arrow, that is, the not long ones if it moves, here is a summary: let's say that the long arrow is the right well, tank man goes to the right but does not make a movement he just stays still and when he finishes the arrow returns to its place.  Thank you for reading

**Comment by cuckydev** [comment]
this is behaviour seen in the original game and will not be changed
