### ISSUE TITLE
compilation fail

### ISSUE THREAD

**Issue by axelpersevalle** [cuckydev/PSXFunkin#62]
hello,

i have a problem since i updated the repo yesterday. All the dependencies are installed (archlinux) and i got this.
Also i don't have understood for the .dat file
[build_psxfunkin.txt](https://github.com/cuckydev/PSXFunkin/files/7273328/build_psxfunkin.txt)

best regards

**Comment by cuckydev** [comment]
You didn't read the `Copying PsyQ files` part of COMPILE.md
