### ISSUE TITLE
Issue on Week 4 Milf

### ISSUE THREAD

**Issue by FNFfan1** [cuckydev/PSXFunkin#7]
Issue on Week 4 song Milf

So when playing, occasionally it freezes. 
![Screenshot_20210628-162804](https://user-images.githubusercontent.com/84652609/123700148-1659a100-d82e-11eb-9aa7-80c32f74a680.jpg)
I don't know if it has to do with the fact that I'm using an emulator, but yeah.

**Comment by BurAndBY** [comment]
> I don't know if it has to do with the fact that I'm using an emulator, but yeah.

EPSXE?

**Comment by FNFfan1** [comment]
No, I'm using the Duckstation emulator on Android.
