### ISSUE TITLE
unblocked games wtf 

### ISSUE THREAD

**Issue by dghnig** [cuckydev/PSXFunkin#70]
it wont let me play friday night funkin on it and it makes me mad because it is my favorite game.

**Comment by UNSTOP4BLE** [comment]
What lmao

**Comment by zeriben** [comment]
So sad im crying!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! so mad



also hello funkin-nightly-github! : D

**Comment by g3yt** [comment]
I am so mad! And sad! I cano't play Friday night funking on my school Chromebook!!!!!!!!!!!!!1!

**Comment by IgorSou3000** [comment]
so sad..

**Comment by UNSTOP4BLE** [comment]
weri







helo funk-nightly-github!11!!

**Comment by DreamcastNick** [comment]
brutus music

**Comment by triangles15** [comment]
that’s craaazy 




I’m talking in nightly github how cool
